version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /go/image
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /go/pkg
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
